"""mdorder, abspath, generated, renderer, finetype and rowheight: files, tools and the built deck."""
import json
import tempfile
import unittest
import zipfile
from pathlib import Path

from fixtures import page, project, reader, recording, use

import abspath
import finetype
import generated
import mdorder
import renderer
import rowheight
from bidkit.pptxread import Built
from bidkit.tests.test_measure import tiny_font


class Base(unittest.TestCase):
    extra: dict = {}

    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.root = Path(self.tmp.name)
        (self.root / "baselines").mkdir()
        self.deck = project(self.root, {"checks": {"baselines": "baselines"}, **self.extra})

    def tearDown(self):
        self.tmp.cleanup()

    def read(self, slides=(), **kw):
        return reader(self.deck, recording(list(slides), **kw))


class MdOrderTests(Base):
    extra = {"manuscript": {"dir": ".", "declaration": "<!--\\s*md:"}}
    PAGE = '<Use template="page" title="t"><Slot name="body"/></Use>'

    def seq(self, files):
        return mdorder.find(self.read(files=files), self.deck)

    def test_a_page_inherits_the_declaration_above_it_and_the_first_source_decides(self):
        text = f"<!-- md: a/01.md -->{self.PAGE}{self.PAGE}<!-- md: a/02.md, a/09.md · Ⅲ-1 03 -->{self.PAGE}"
        seq, back = self.seq({"pages/x.xml": text})
        self.assertEqual([md for _, md in seq], ["a/01.md", "a/01.md", "a/02.md"])
        self.assertEqual(back, [])

    def test_an_annex_page_is_not_a_body_page(self):
        seq, _ = self.seq({"pages/x.xml": '<!-- md: z/01.md --><Use template="annex-part" title="t"/>'})
        self.assertEqual(seq, [])

    def test_a_section_appended_to_the_wrong_file_is_reported(self):
        files = {"pages/1.xml": f"<!-- md: a/00.md -->{self.PAGE}<!-- md: a/03.md -->{self.PAGE}",
                 "pages/2.xml": f"<!-- md: a/01.md -->{self.PAGE}"}
        _, back = self.seq(files)
        self.assertEqual([(f, before) for f, _, _, before in back], [("2.xml", "a/03.md")])


class AbsPathTests(Base):
    def found(self, files, **cfg):
        self.deck.data["checks"]["abspath"] = cfg
        paths, tracked, _ = abspath.find(self.read(files=files), self.deck)
        return [(n, v) for n, _, v in paths if abspath.ABS.match(v)], tracked

    def test_absolute_paths_in_sources_and_the_build_file(self):
        files = {"pages/a.xml": '<Use template="figure" src="/Users/x/a.svg"/><Image src="assets/b.png"/>'
                                 '<!-- <Image src="/commented/out.png"/> -->',
                 "slideglance.json": json.dumps({"build": {"fonts": ["/opt/f.ttf", "fonts/g.ttf"],
                                                           "url": "https://example.org/x"}})}
        bad, _ = self.found(files)
        self.assertEqual(bad, [("pages/a.xml", "/Users/x/a.svg"), ("slideglance.json", "/opt/f.ttf")])
        fixed = {k: v.replace("/Users/x/", "assets/").replace("/opt/", "fonts/") for k, v in files.items()}
        self.assertEqual(self.found(fixed)[0], [])

    def test_a_scanned_file_is_read_the_same_way(self):
        (self.root / "gen").mkdir()
        (self.root / "gen" / "figures.xml").write_text('<Image src="/home/me/f.png"/>', encoding="utf-8")
        self.assertEqual(self.found({}, scan=["gen/*.xml"])[0], [("gen/figures.xml", "/home/me/f.png")])


class GeneratedTests(Base):
    def test_a_hand_edit_a_stale_generator_and_a_matching_record(self):
        (self.root / "tools").mkdir()
        (self.root / "tools" / "make.py").write_text("print(1)\n", encoding="utf-8")
        self.deck.data["checks"]["generated"] = {"generator": r"tools/[a-z]+\.py"}
        files = {"pages/a.xml": "<!-- generated by tools/make.py -->\n<Fragment/>", "pages/b.xml": "<Fragment/>"}
        now = generated.generated(self.read(files=files), self.deck)
        self.assertEqual(list(now), ["deck/pages/a.xml"])
        self.assertEqual(generated.compare(now, json.loads(json.dumps(now))), [])
        edited = generated.generated(self.read(files={"pages/a.xml": files["pages/a.xml"] + " "}), self.deck)
        self.assertIn("differs from the record", generated.compare(edited, now)[0][1])
        (self.root / "tools" / "make.py").write_text("print(2)\n", encoding="utf-8")
        regen = generated.generated(self.read(files=files), self.deck)
        self.assertIn("not regenerated", generated.compare(regen, now)[0][1])
        self.assertIn("not in the record", generated.compare(now, {})[0][1])


class RendererTests(unittest.TestCase):
    def test_versions(self):
        self.assertIsNone(renderer.judge("slideglance 0.4.2", "0.4.0"))
        self.assertIn("0.3.9", renderer.judge("slideglance 0.3.9", "0.4.0"))
        self.assertIn("no version", renderer.judge("usage: slideglance", "0.4.0"))
        self.assertIsNone(renderer.judge("slideglance 0.10.0", "0.9.1"))


EMU = 9525          # per px at a 794px page written 794 * 9525 wide


def sp(x, y, w, h, body="", fill=True):
    pr = (f'<a:xfrm><a:off x="{x * EMU}" y="{y * EMU}"/><a:ext cx="{w * EMU}" cy="{h * EMU}"/></a:xfrm>'
          + ('<a:solidFill><a:srgbClr val="F5F6F8"/></a:solidFill>' if fill else "<a:noFill/>"))
    return f"<p:sp><p:spPr>{pr}</p:spPr>{body}</p:sp>"


def run(t, size=800, colour="646B77", bold=False):
    b = ' b="1"' if bold else ""
    return (f'<a:r><a:rPr sz="{size}"{b}><a:solidFill><a:srgbClr val="{colour}"/></a:solidFill></a:rPr>'
            f"<a:t>{t}</a:t></a:r>")


def pptx(path: Path, *slides: str) -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(path, "w") as z:
        z.writestr("ppt/presentation.xml", f'<p:presentation><p:sldSz cx="{794 * EMU}" cy="1"/></p:presentation>')
        for i, xml in enumerate(slides, 1):
            z.writestr(f"ppt/slides/slide{i}.xml", xml)
    return path


class RowHeightTests(Base):
    extra = {"output": "deck/out/main.pptx", "page": {"w": 794}}

    def found(self, *shapes):
        pptx(self.root / "deck" / "out" / "main.pptx", "".join(shapes))
        return rowheight.check(Built.for_deck(self.deck), self.deck)

    def test_framed_boxes_of_unequal_height_are_reported(self):
        self.assertEqual(len(self.found(sp(10, 100, 200, 60), sp(230, 100, 200, 80))), 1)
        self.assertEqual(self.found(sp(10, 100, 200, 80), sp(230, 100, 200, 80)), [])

    def test_a_wrapper_an_unframed_box_and_a_marker_are_not_neighbours(self):
        self.assertEqual(self.found(sp(10, 100, 420, 90), sp(10, 100, 200, 60), sp(230, 100, 200, 60)), [])
        self.assertEqual(self.found(sp(10, 100, 200, 60), sp(230, 100, 200, 80, fill=False)), [])
        marker = sp(230, 100, 18, 18, "<p:txBody><a:p><a:r><a:t>3</a:t></a:r></a:p></p:txBody>")
        self.assertEqual(self.found(sp(10, 100, 200, 60), marker), [])
        bullet = sp(230, 100, 6, 6)
        self.assertEqual(self.found(sp(10, 100, 200, 20), bullet), [])
        self.assertEqual(len(self.found(sp(10, 100, 200, 20), sp(230, 100, 30, 30))), 1)

    def test_a_group_counts_only_when_it_draws_its_own_frame(self):
        def group(h, fill):
            inner = sp(0, 0, 200, h, fill=fill)
            return (f'<p:grpSp><p:grpSpPr><a:xfrm><a:off x="{10 * EMU}" y="{100 * EMU}"/>'
                    f'<a:ext cx="{200 * EMU}" cy="{h * EMU}"/></a:xfrm></p:grpSpPr>{inner}</p:grpSp>')
        self.assertEqual(len(self.found(group(60, True), sp(230, 100, 200, 80))), 1)
        self.assertEqual(self.found(group(60, False), sp(230, 100, 200, 80)), [])


class FineTypeTests(Base):
    extra = {"output": "deck/out/main.pptx", "page": {"w": 794}, "type": {"floor": 8}}

    def found(self, *shapes):
        font = tiny_font(self.root / "Face-Regular.ttf", {c: 1000 for c in "가나다 ."})
        tiny_font(self.root / "Face-Bold.ttf", {c: 1000 for c in "가나다 ."})
        pptx(self.root / "deck" / "out" / "main.pptx", "".join(shapes))
        rec = recording([page(1, use("prose"))])
        rec["resources"]["sg://deck"] += f"options fonts={font},{self.root / 'Face-Bold.ttf'} masterPptx=-\n"
        r = reader(self.deck, rec)
        r.vocab.data["fonts"] = {"sans": "Face"}
        return finetype.find(r, self.deck, Built.for_deck(self.deck))[0]

    def box(self, x, w, *runs):
        return sp(x, 100, w, 40, "<p:txBody><a:p>" + "".join(runs) + "</a:p></p:txBody>", fill=False)

    def test_a_paragraph_of_fine_print_is_reported(self):
        long = "가나다 " * 12
        self.assertEqual(len(self.found(self.box(100, 60, run(long)))), 1)
        self.assertEqual(self.found(self.box(100, 600, run("가나다"))), [])              # one line
        self.assertEqual(self.found(self.box(100, 60, run(long, colour="2E3138"))), [])  # body ink
        self.assertEqual(self.found(self.box(100, 60, run(long, size=1000))), [])        # above the floor

    def test_a_value_row_beside_a_bold_label_is_not_an_aside(self):
        label = self.box(30, 60, run("가나", bold=True))
        self.assertEqual(self.found(label, self.box(100, 60, run("가나다 " * 12))), [])


if __name__ == "__main__":
    unittest.main()
