"""One figure module, as a worked example. Copy it into the project and rename it
per chapter (`tools/diagrams/ch01.py`).

A module draws at import time and calls `save()` once per figure. The skill's
`scripts/docfigures/build.py` runs every module the project's
`.claude/document-figures.json` lists, with the library on the import path, so
`from common import ...` reaches the shared drawing layer and the project
never carries a copy of it. A figure is regenerated by running the build,
never by hand-editing the SVG: the SVG is a build artifact.
"""
from common import (CARD, CONTENT_W, FULL, HAIRLINE, PAD, STROKE, card, cards_row,
                    canvas, figure, row, save)


def fig_stages():
    """Three stages in sequence, with a record that spans them."""
    c = canvas(1200, 320)
    stages = [(c.blue, "Collect", ["channel adapters", "raw retained"]),
              (c.orange, "Structure", ["fields extracted", "reviewer confirms"]),
              (c.green, "Decide", ["owner reviews", "outcome recorded"])]
    # The columns span the content width; the lint fails a side gap over 40.
    x0, gap, top = 38, 36, 40
    xs, w = row(len(stages), gap, width=CONTENT_W, x0=x0)
    # cards_row sizes every card from the tallest content and pads evenly, so
    # the row never carries a band of paper under its text.
    boxes = cards_row(c, xs, top, w, [(name, lines) for _, name, lines in stages],
                      accents=[accent for accent, _, _ in stages],
                      band=True, title_size=CARD)
    h = boxes[0][3]
    for i in range(len(stages) - 1):
        c.line(xs[i] + w, top + h / 2, xs[i + 1], top + h / 2,
               color=c.t["fg_dim"], sw=STROKE, marker=c.t["fg_dim"])
    card(c, x0, top + h + 34, CONTENT_W, c.teal, "Record",
         ["every stage writes its inputs, its outputs and who approved them"],
         sw=HAIRLINE, pad=PAD)
    save(c, "fig-example-stages", board=FULL)


@figure(plain=True)
def fig_one_line_each():
    """A figure whose boxes hold one line each declares itself plain, so those
    lines are not bulleted."""
    c = canvas(1200, 200)
    xs, w = row(2, 36, width=CONTENT_W, x0=38)
    cards_row(c, xs, 40, w, [("Input", ["one source"]), ("Output", ["one report"])],
              accents=[c.blue, c.green])
    save(c, "fig-example-plain", board=FULL)


fig_stages()
fig_one_line_each()
