"""One figure module, as a worked example. Copy it and rename per chapter.

A module draws at import time and calls `save()` once per figure. `build.py`
runs every module beside it, so a figure is regenerated by running the build,
never by hand-editing the SVG — the SVG is a build artifact.
"""
from common import canvas, save, SANS


def fig_stages():
    """Three stages in sequence, with a layer that spans them."""
    c = canvas(1200, 320)

    stages = [(c.blue, "Collect", ["channel adapters", "raw retained"]),
              (c.orange, "Structure", ["fields extracted", "reviewer confirms"]),
              (c.green, "Decide", ["owner reviews", "outcome recorded"])]

    # 24 … 1176 — the lint fails a side gap over 40 units.
    x0, w, gap, top, h = 24, 360, 36, 40, 150
    for i, (accent, name, lines) in enumerate(stages):
        x = x0 + i * (w + gap)
        c.rrect(x, top, w, h, rx=12, fill=c.t["box"], stroke=accent, sw=1.6,
                shadow=True)
        # Only the corners that follow the card's outline are rounded.
        c.band(x, top, w, 38, 12, accent, 0.14)
        c.text(x + 18, top + 26, name, size=13.25, color=accent, family=SANS,
               weight=700)
        for j, line in enumerate(lines):
            c.text(x + 18, top + 66 + j * 23, "· " + line, size=11.25,
                   color=c.t["fg"], family=SANS)
        if i < len(stages) - 1:
            c.line(x + w, top + h / 2, x + w + gap, top + h / 2,
                   color=c.t["fg_dim"], sw=1.8)

    band_y = top + h + 34
    c.rrect(x0, band_y, 3 * w + 2 * gap, 74, rx=12, fill=c.t["panel"],
            stroke=c.teal, sw=1.6)
    c.text(x0 + 18, band_y + 28, "Record", size=13.25, color=c.teal,
           family=SANS, weight=700)
    c.text(x0 + 18, band_y + 54,
           "every stage writes its inputs, its outputs and who approved them",
           size=11.25, color=c.t["fg"], family=SANS)

    save(c, "fig-example-stages")


fig_stages()
