"""One figure module, as a worked example. Copy it and rename per chapter.

A module draws at import time and calls `save()` once per figure. `build.py`
runs every module beside it, so a figure is regenerated by running the build,
never by hand-editing the SVG — the SVG is a build artifact.
"""
from common import (BODY, CARD, HAIRLINE, STROKE, cards_row, canvas, save,
                    SANS)


def fig_stages():
    """Three stages in sequence, with a layer that spans them."""
    c = canvas(1200, 320)

    stages = [(c.blue, "Collect", ["channel adapters", "raw retained"]),
              (c.orange, "Structure", ["fields extracted", "reviewer confirms"]),
              (c.green, "Decide", ["owner reviews", "outcome recorded"])]

    # 24 … 1176 - the lint fails a side gap over 40 units.
    x0, w, gap, top = 24, 360, 36, 40
    xs = [x0 + i * (w + gap) for i in range(len(stages))]
    # cards_row sizes every card from the tallest content and pads evenly, so
    # the row never carries a band of paper under its text. A fixed height here
    # is what ROW-PADDING-UNEVEN reports.
    boxes = cards_row(
        c, xs, top, w,
        [(name, lines) for _, name, lines in stages],
        accents=[accent for accent, _, _ in stages],
        band=True, title_size=CARD, size=BODY)
    h = boxes[0][3]
    for i in range(len(stages) - 1):
        c.line(xs[i] + w, top + h / 2, xs[i] + w + gap, top + h / 2,
               color=c.t["fg_dim"], sw=STROKE)

    band_y = top + h + 34
    c.rrect(x0, band_y, 3 * w + 2 * gap, 74, rx=12, fill=c.t["panel"],
            stroke=c.teal, sw=HAIRLINE)
    c.text(x0 + 18, band_y + 28, "Record", size=13.25, color=c.teal,
           family=SANS, weight=700)
    c.text(x0 + 18, band_y + 54,
           "every stage writes its inputs, its outputs and who approved them",
           size=11.25, color=c.t["fg"], family=SANS)

    save(c, "fig-example-stages")


fig_stages()
